name: .NET Core Console CI

on:
  push:
    branches: [ "main" ]  
  pull_request:
    branches: [ "main" ] 

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]  

    env:
      Solution_Name: Lab6/Lab6.sln  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  

    - name: Restore NuGet packages
      run: dotnet restore ${{ env.Solution_Name }}  

    - name: Build solution
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore 

    - name: Run LibraryTests
      run: dotnet test Lab6/LibraryTests.csproj --no-restore --verbosity normal  

    - name: Run UserTests
      run: dotnet test Lab6/UserTests.csproj --no-restore --verbosity normal  

    - name: Run BookTests
      run: dotnet test Lab6/BookTests.csproj --no-restore --verbosity normal  
